notes/urls.py
from django.urls import path

from .views import sign_up_view, create_user, login_view, HomeView, logout_view, PostNoteView, SettingsView, follow, unfollow
from .views import NoteDetailView, delete_note, NoteUpdateView, redirect_to_home
from .views import NotesView, UsersView, UserView, UserFollowView, UserFollowerView
from .views import password_change, delete_account

app_name = 'notes'
urlpatterns = [
    path('', redirect_to_home, name='redirect_to_home'),

    path('login/', login_view, name='login'),
    path('signup/', sign_up_view, name='signup'),
    path('create_user/', create_user, name='create_user'),
    path('logout/', logout_view, name='logout'),

    path('home/', HomeView.as_view(), name='home'),
    path('notes/', NotesView.as_view(), name='notes'),
    path('users/', UsersView.as_view(), name='users'),
    path('user/<int:pk>', UserView.as_view(), name='user_page'),
    path('user/<int:pk>/follow', UserFollowView.as_view(),
         name='user_follow_list'),
    path('user/<int:pk>/follower', UserFollowerView.as_view(),
         name='user_follower_list'),

    path('follow/<int:pk>', follow, name='follow'),
    path('unfollow/<int:pk>', unfollow, name='unfollow'),

    path('settings/<int:pk>', SettingsView.as_view(), name='settings'),

    path('post/', PostNoteView.as_view(), name='post_note'),

    path('note/<int:pk>', NoteDetailView.as_view(), name='note_detail'),
    path('note/edit/<int:pk>', NoteUpdateView.as_view(), name='note_update'),
    path('note/delete/<int:pk>', delete_note, name='note_delete'),

    path('password_change/', password_change, name='password_change'),
    path('delete_account/<int:pk>', delete_account, name='delete_account'),


]

notes_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

settings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

notes/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import mark_safe
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from markdown import markdown


class Account(AbstractUser):
    icon = models.ImageField(
        upload_to='icons/', blank=True, default='icons/default.png'
    )

    icon_small = ImageSpecField(
        source='icon',
        processors=[ResizeToFill(32, 32)],
        format='JPEG',
    )

    icon_middle = ImageSpecField(
        source='icon',
        processors=[ResizeToFill(70, 70)],
        format='JPEG'
    )

    icon_big = ImageSpecField(
        source='icon',
        processors=[ResizeToFill(150, 150)],
        format='JPEG'
    )

    def __str__(self):
        return self.username


class Follow(models.Model):
    follow = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name='follow_id'
    )
    follower = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name='follower_id'
    )

    def __str__(self):
        return f'{self.follow.username}-{self.follower.username}'


class Notes(models.Model):
    author = models.ForeignKey(Account, on_delete=models.CASCADE)
    text = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    images = models.ImageField(upload_to='', blank=True, default='')

    class Meta:
        ordering = ['-created_at']

    def get_markdown(self):
        return markdown(self.text)

    def get_text_as_markdown(self):
        # fenced_code - ```code```
        # nl2br - new line to break
        # https://python-markdown.github.io/reference/
        return mark_safe(markdown(
            self.text, extensions=['fenced_code', 'attr_list', 'nl2br'],
            safe_mode='escape'
        ))

    def get_format_created_at(self):
        return self.created_at.strftime("%Y-%m-%d %H:%M:%S")

    def __str__(self):
        return f'{self.author}:{self.text[:5]}'

notes/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.utils import IntegrityError
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Account, Follow, Notes


# Auth -------------------------------------------------------------------------
@login_required
def redirect_to_home(request):
    return redirect('notes:home')


def sign_up_view(request):
    return render(request, 'notes/signup.html')


def create_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            Account.objects.create_user(username, password=password)
            return redirect('notes:login')
        except IntegrityError:
            return redirect('notes:signup')

    if request.method == 'GET':
        return redirect('notes:signup')


def login_view(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('notes:home')
        else:
            return render(request, 'notes/login.html')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('notes:home')
        else:
            return render(request, 'notes/login.html',
                          {'error': 'ユーザ名かパスワードが間違っています'})


def logout_view(request):
    logout(request)
    return redirect('notes:login')


# Home--------------------------------------------------------------------------

class HomeView(ListView):
    template_name = 'notes/home.html'
    context_object_name = 'notes_list'

    def get_queryset(self):

        if self.request.user.is_authenticated:
            user_id = self.request.user.id
            follows = Follow.objects.filter(follow=user_id)
            follow_list = [str(user_id)] + [str(f.follower.id) for f in follows]
        else:
            follows = Follow.objects.all()
            follow_list = [str(f.follower.id) for f in follows]

        if self.request.GET.get('q'):
            return Notes.objects.filter(
                author__in=follow_list,
                text__contains=self.request.GET['q']).order_by('-created_at')
        else:
            return Notes.objects.filter(
                author__in=follow_list).order_by('-created_at')


# All notes---------------------------------------------------------------------

class NotesView(ListView):
    template_name = 'notes/all_notes.html'
    context_object_name = 'notes_list'

    def get_queryset(self):
        if self.request.GET.get('q'):
            search_word = self.request.GET['q']
            return Notes.objects.filter(
                text__contains=search_word).order_by('-created_at')
        else:
            return Notes.objects.all().order_by('-created_at')


# Note  ------------------------------------------------------------------------

class PostNoteView(LoginRequiredMixin, CreateView):
    model = Notes
    template_name = 'notes/post_note.html'

    fields = ['author', 'text']
    success_url = reverse_lazy('notes:home')


class NoteUpdateView(LoginRequiredMixin, UpdateView):
    model = Notes
    template_name = 'notes/note_update.html'
    context_object_name = 'note'

    fields = ['author', 'text']
    success_url = reverse_lazy('notes:home')


class NoteDetailView(DetailView):
    model = Notes
    template_name = 'notes/note_detail.html'
    context_object_name = 'note'


@login_required
def delete_note(request, pk):
    Notes.objects.get(pk=pk).delete()
    return redirect('notes:home')


# Users ------------------------------------------------------------------------

class UsersView(ListView):
    template_name = 'notes/users.html'
    context_object_name = 'users_list'

    def get_queryset(self):
        if self.request.GET.get('q'):
            return Account.objects.filter(
                username__contains=self.request.GET['q'])
        else:
            return Account.objects.all()


# User -------------------------------------------------------------------------

class UserView(ListView):
    model = Notes
    template_name = 'notes/user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = self.request.user.id
        target_user = Account.objects.get(pk=self.kwargs['pk'])

        context['target_user'] = target_user
        context['num_follow'] = Follow.objects.filter(
            follow=target_user).count()
        context['num_follower'] = Follow.objects.filter(
            follower=target_user).count()

        if self.request.user.is_authenticated:
            context['is_follow'] = bool(Follow.objects.filter(follow=login_user,
                                                              follower=target_user).count())

        if self.request.GET.get('q'):
            search_word = self.request.GET['q']
            context['target_user_notes_list'] = Notes.objects.filter(
                author=target_user,
                text__contains=search_word).order_by('-created_at')
        else:
            context['target_user_notes_list'] = Notes.objects.filter(
                author=target_user).order_by('-created_at')
        return context


# Relation ---------------------------------------------------------------------

class UserFollowView(ListView):
    template_name = 'notes/user_relationship.html'
    context_object_name = 'users_list'

    def get_queryset(self):
        follows_obj = Follow.objects.filter(follow=self.kwargs['pk'])
        follows_pk = [str(follow_obj.follower.pk) for follow_obj in
                      follows_obj]

        if self.request.GET.get('q'):
            search_word = self.request.GET['q']
            return Account.objects.filter(pk__in=follows_pk,
                                          username__contains=search_word)
        else:
            return Account.objects.filter(pk__in=follows_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['relation'] = 'Follow'
        return context


class UserFollowerView(ListView):
    template_name = 'notes/user_relationship.html'
    context_object_name = 'users_list'

    def get_queryset(self):
        followers_obj = Follow.objects.filter(follower=self.kwargs['pk'])
        followers_pk = [str(follower_obj.follow.pk) for follower_obj in followers_obj]

        if self.request.GET.get('q'):
            search_word = self.request.GET['q']
            return Account.objects.filter(pk__in=followers_pk,
                                          username__contains=search_word)
        else:
            return Account.objects.filter(pk__in=followers_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['relation'] = 'Follower'
        return context


@login_required
def follow(request, pk):
    f = Follow.objects.create(follow=request.user,
                              follower=Account.objects.get(pk=pk))
    f.save()
    return redirect('notes:user_page', pk=pk)


@login_required
def unfollow(request, pk):
    f = Follow.objects.filter(follow=request.user).filter(follower=pk)
    f.delete()
    return redirect('notes:user_page', pk=pk)


# Settings----------------------------------------------------------------------

class SettingsView(LoginRequiredMixin, UpdateView):
    model = Account
    template_name = 'notes/settings.html'
    fields = ['username', 'icon']
    success_url = reverse_lazy('notes:home')


@login_required
def password_change(request):
    if request.method == 'POST':
        user = request.user
        if user.check_password(request.POST['old_password']):
            p1 = request.POST['new_password1']
            p2 = request.POST['new_password2']

            if p1 == p2:
                user.set_password(p1)
                user.save()
                update_session_auth_hash(request, user)
                return redirect('notes:settings', pk=user.pk)
            else:
                return render(request, 'notes/settings.html',
                              {'error': 'p1 != p2'})
        else:
            return render(request, 'notes/settings.html',
                          {'error': 'old password != raw password'})


@login_required
def delete_account(request, pk):
    if request.method == 'POST':
        account = Account.objects.get(pk=pk)
        password = request.POST['delete-password']

        if account.check_password(password):
            account.delete()
            return redirect('notes:home')
        else:
            return render(request, 'notes/settings.html',
                          {'error': 'password is wrong'})

notes/templates/notes/all_notes.html
{% extends 'notes/app_base.html' %}
{% load static %}


<!--Head-->

{% block title %}
All notes
{% endblock title %}

{% block search_form_placeholder %}
Search notes
{% endblock search_form_placeholder %}

{% block active_all_notes %}
active
{% endblock active_all_notes %}

<!--Body-->

{% block content_title %}
Notes
{% endblock content_title %}

{% block content %}
<div>
  {% for note in notes_list %}
  <div class="note-content">
    <div class="note-content__icon">
      <a href="{% url 'notes:user_page' note.author.id %}">
        <img class="user-icon" src="{{ note.author.icon_small.url }}" alt="N">
      </a>
    </div>

    <div class="note-content__content">
      <p class="note-content__content-author"><a
              href="{% url 'notes:user_page' note.author.id %}">@{{ note.author }}</a> {{ note.get_format_created_at }}</p>
      <div  class="note-content__content-area"
           onclick="location.href='{% url 'notes:note_detail' note.id %}'">
        {{ note.get_text_as_markdown }}
      </div>
    </div>
  </div>
  <hr>
  {% endfor %}
</div>
{% endblock content %}

notes/templates/notes/app_base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'notes/app_base.css' %}">

    <!-- Markdown Editor - SimpleMDE   -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

    <title>{% block title %}{% endblock title %}</title>
  </head>

  <body>
    <header class="header flex-c r-hidden">
      <div class="header-container flex-r">
        <ul class="header__item-list flex-r">
          <li class="header__service-name r-hidden">
            <a href="{% url 'notes:home' %}" class="decoration-none">GNotes</a>
          </li>
          <li>
            <form class="header__search-form {% block show_search_form %}{% endblock show_search_form %}" action="" method="GET">
              <input class="header__search-form-input" name="q" type="text" placeholder="{% block search_form_placeholder %}{% endblock search_form_placeholder %}">
            </form>
          </li>
        </ul>
        <ul class="header__item-list flex-r responsive-r-justify">
          {% if user.id %}
          <li><a href="{% url 'notes:user_page' user.pk %}"><img class="r-hidden" src="{{ user.icon_small.url }}" alt="icon"></a></li>
          <li><a class="btn r-hidden" href="{% url 'notes:logout' %}">log out</a></li>
          {% else %}
          <li><a class="btn r-hidden" href="{% url 'notes:login' %}">Sign in</a></li>
          <li><a class="btn r-hidden" href="{% url 'notes:signup' %}">Sign up</a></li>
          {% endif %}

        </ul>
      </div>
    </header>

    <div class="content-container flex-r">
      <div class="sidebar flex-c">
        <ul class="sidebar__item-list list-none">
          <li class="sidebar__item">
            <a class="sidebar__item-link {% block active_home %}{% endblock active_home %}"
               href="{% url 'notes:home' %}">
              <span data-feather="home"></span>
              <span class="sidebar__item-description">Home</span>
            </a>
          </li>
          <li class="sidebar__item">
            <a class="sidebar__item-link {% block active_all_notes %}{% endblock active_all_notes %}"
               href="{% url 'notes:notes' %}">
              <span data-feather="book"></span>
              <span class="sidebar__item-description">Notes</span>
            </a>
          </li>
          <li class="sidebar__item">
            <a class="sidebar__item-link {% block active_users %}{% endblock active_users %}"
               href="{% url 'notes:users' %}">
              <span data-feather="users"></span>
              <span class="sidebar__item-description">Users</span>
            </a>
          </li>
          {% if user.id %}
          <li class="sidebar__item">
            <a class="sidebar__item-link {% block active_mypage %}{% endblock active_mypage %}"
               href="{% url 'notes:user_page' user.id %}">
              <span data-feather="user"></span>
              <span class="sidebar__item-description">My page</span>
            </a>
          </li>
          <li class="sidebar__item">
            <a class="sidebar__item-link {% block active_settings %}{% endblock active_settings %}"
               href="{% url 'notes:settings' user.id %}">
              <span data-feather="settings"></span>
              <span class="sidebar__item-description">Settings</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

      <div class="content-wrapper">
        <div class="content">
          <div class="content__title-container flex-r {% block hidden %}{% endblock hidden %}">
            <h1 class="content__title">{% block content_title %}{% endblock content_title %}</h1>

            <div class="r-nav r-visible">

              <div class="r-nav-search-wrap">
                <form action="" method="GET">{% csrf_token %}
                  <input class="r-nav-search-form" type="text" name="q" placeholder="search...">
                  <a class="r-nav-icon r-nav-search-form-submit"><span data-feather="search"></span></a>
                </form>
              </div>


              <div class="r-nav-menu">
                <input id="r-nav-input" type="checkbox" class="r-nav-hidden">
                <label class="r-nav-open" for="r-nav-input"><span class="r-nav-icon" data-feather="menu"></span></label>
                <label class="r-nav-close r-nav-hidden" for="r-nav-input"></label>
                <div class="r-nav-menu-content flex-c">

                  <div class="drawer-user-container">
                    {% if user.id %}
                    <img id="icon-preview" src="{{ user.icon_big.url }}" alt="icon">
                    <p>@{{ user.get_username }}</p>
                    {% else %}
                    <img id="icon-preview" src="/media/icons/default.png" alt="icon">
                    <p>Guest</p>
                    {% endif %}
                  </div>

                  {% if user.id %}
                  <a class="drawer-item deco-none" href="{% url 'notes:logout' %}">
                    <span class="drawer-icon" data-feather="log-out"></span>Log out
                  </a>
                  {% else %}
                  <a class="drawer-item deco-none" href="{% url 'notes:login' %}">
                    <span class="drawer-icon" data-feather="log-in"></span>Sign in
                  </a>
                  <a class="drawer-item deco-none" href="{% url 'notes:signup' %}">
                    <span class="drawer-icon" data-feather="edit-3"></span>Sign up
                  </a>
                  {% endif %}

                </div>
              </div>
            </div>
          </div>
          {% block content_header %}{% endblock content_header %}
          {% block content %}{% endblock content %}

          {% if user.id %}
          <div class="edit-btn {% block edit-btn-hidden %}{% endblock edit-btn-hidden %}">
            <a class="deco-none blue" href="{% url 'notes:post_note' %}">
              <span class="fa edit-feather" data-feather="edit"></span>
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Feather icon - https://feathericons.com/ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="{% static 'notes/app_base.js' %}"></script>

    <!-- Markdown Highlighter - highlightjs   -->
    <link rel="stylesheet"
        href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/styles/dracula.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

  </body>
</html>

notes/templates/notes/detail.html
{% extends 'app_base.html' %}
{% load static %}


<!--Head-->

{% block css_link %}
    <link rel="stylesheet" href="{% static 'notes/app_base.css' %}">
{% endblock css_link %}

{% block title %}
    @{{ target_user }}
{% endblock title %}


{% block search_form %}
    {% url 'notes:search_user_redirect' self_pk %}
{% endblock search_form %}

{% block search_form_placeholder %}
    Search notes
{% endblock search_form_placeholder %}



{% block active_users %}
    active
{% endblock active_users %}


<!--Body-->

{% block board_title %}
<img src="{{ target_user.icon_big.url }}" alt="N">
@ {{ target_user }}

{% if user.id != self_pk %}
    {% if is_follow %}
        <a href="{% url 'notes:unfollow' self_pk %}" class="btn btn-danger btn" role="button" aria-pressed="true">unfollow</a>
    {% else %}
        <a href="{% url 'notes:follow' self_pk %}" class="btn btn-primary btn" role="button" aria-pressed="true">follow</a>
    {% endif %}
{% endif %}

<a href="{% url 'notes:follow_list' self_pk %}">
<button type="button" class="btn btn-success">
    Follow <span class="badge badge-light">{{ num_follow }}</span>
</button>
</a>

<a href="{% url 'notes:follower_list' self_pk %}">
<button type="button" class="btn btn-success">
  Follower <span class="badge badge-light">{{ num_follower }}</span>
</button>
</a>

{% endblock board_title %}


{% block content %}
 <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 maincontent">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Recent notes</h6>
      {% for note in notes_list %}
        <div class="media text-muted pt-3">
            <a href="{% url 'notes:detail' note.noted_user_id.id %}">
                <img src="{{ note.noted_user_id.icon_small.url }}" alt="N">
            </a>
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">
                <a href="{% url 'notes:detail' note.noted_user_id.id %}">@{{ note.noted_user_id }}</a>  {{ note.created_at.hour }}:{{ note.created_at.minute }}   {{ note.created_at.month }}/{{ note.created_at.day }}
            </strong>
          </p>
        </div>

      <div style="margin:0 30px;" onclick="location.href='{% url 'notes:note_detail' note.id %}'">
            {{ note.get_text_as_markdown }}
        </div>
      {% endfor %}
    <small class="d-block text-right mt-3">
      <a href="#">All updates</a>
    </small>
  </div>
 </main>
{% endblock content %}

notes/templates/notes/note_detail.html
{% extends 'notes/app_base.html' %}
{% load static %}

<!--Head-->

{% block title %}
Home
{% endblock title %}

{% block search_form_placeholder %}
Search notes
{% endblock search_form_placeholder %}

{% block active_home %}
active
{% endblock active_home %}

<!--Body-->

{% block content_title %}
Note
{% endblock content_title %}

{% block edit-btn-hidden %}
hidden
{% endblock edit-btn-hidden %}

{% block content %}
<div>
  {% if user.id == note.author.id %}
  <div class="note-detail__btn-area" style="text-align: right;">
    <a href="{% url 'notes:note_update' note.id %}" class="btn"
       role="button" aria-pressed="true">Edit</a>
    <a href="{% url 'notes:note_delete' note.id %}" class="btn red"
       role="button" aria-pressed="true">Delete</a>
  </div>
  <hr>
  {% endif %}

  <div class="note-content">
    <div class="note-content__icon">
      <a href="{% url 'notes:user_page' note.author.id %}">
        <img src="{{ note.author.icon_small.url }}" alt="N">
      </a>
    </div>

    <div class="note-content__content">
      <p class="note-content__content-author"><a
              href="{% url 'notes:user_page' note.author.id %}">@{{ note.author }}</a> {{ note.get_format_created_at }}</p>
      <div  class="note-content__content-area"
           onclick="location.href='{% url 'notes:note_detail' note.id %}'">
        {{ note.get_text_as_markdown }}
      </div>
    </div>
  </div>
  <hr>
</div>
{% endblock content %}

notes/templates/notes/settings.html
{% extends 'notes/app_base.html' %}
{% load static %}


<!--Head-->

{% block title %}
Settings
{% endblock title %}

{% block active_settings %}
active
{% endblock active_settings %}

{% block show_search_form %}
show-none
{% endblock show_search_form %}


<!--Body-->

{% block content_title %}
Settings
{% endblock content_title %}

{% block edit-btn-hidden %}
hidden
{% endblock edit-btn-hidden %}

{% block content %}
<div class="settings-container flex-r">

  <div class="settings-left sub-container">
    <div class="form-group">
      <form class="settings-form" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <label>Icon</label>
        <img id="icon-preview" src="{{ user.icon_big.url }}" alt="icon">
        <input type="file" name="icon" onchange="preview_img(this);">
        <input type="hidden" name="username" value="{{ user.get_username }}">
        <button type="submit" class="btn form-btn">Save</button>
      </form>
      <script type="text/javascript">
        function preview_img(input) {
          if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
              el = document.getElementById('icon-preview');
              el.src = e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
          }
        }
      </script>
    </div>

  </div>

  <div class="settings-right sub-container">

    <div class="form-group">
      <form class="settings-form" action="" method="POST">{% csrf_token %}
        <label>User name</label>
        <input type="text" name="username" class="form-input" value="{{ user.get_username }}">
        <button type="submit" class="btn form-btn">Save</button>
      </form>
    </div>

    <hr>

    <div class="form-group">
      <form class="settings-form" action="{% url 'notes:password_change' %}" method="POST">{% csrf_token %}
        {{ error }}
        <label>Old password</label>
        <input type="password" name="old_password" class="form-input" placeholder="Enter old password">
        <label>New password</label>
        <input type="password" name="new_password1" class="form-input" placeholder="Enter new password">
        <label>New password(verify)</label>
        <input type="password" name="new_password2" class="form-input" placeholder="Enter new password again">
        <button type="submit" class="btn form-btn">Change</button>
      </form>
    </div>

    <hr>

    <div class="form-group delete-account">
      <form class="settings-form" action="{% url 'notes:delete_account' user.pk %}" method="POST">{% csrf_token %}
        {{ error }}
        <label>Delete account</label>
        <input type="password" name="delete-password" class="form-input" placeholder="Enter your password">
        <button type="submit" class="btn red">delete</button>
      </form>
    </div>

  </div>
</div>

<hr>
{% endblock content %}

notes/templates/notes/user.html
{% extends 'notes/app_base.html' %}
{% load static %}


<!--Head-->

{% block title %}
  @{{ target_user }}
{% endblock title %}

{% block search_form_placeholder %}
  Search notes
{% endblock search_form_placeholder %}


{% block active_mypage %}
  {% if user.id == target_user.pk %}
  active
  {% endif %}
{% endblock active_mypage %}

{% block active_users %}
  {% if user.id != target_user.pk %}
  active
  {% endif %}
{% endblock active_users %}

{% block hidden %}
hidden
{% endblock hidden %}

{% block edit-btn-hidden %}
hidden
{% endblock edit-btn-hidden %}

<!--Body-->

{% block content_header %}
<div class="user-header flex-r">
  <img class="user-icon" src="{{ target_user.icon_big.url }}" alt="N">

  <div class="user-header__info flex-c">
    <div class="user-header__info__username flex-r">
      @ {{ target_user }}

      {% if user.id %}
        {% if user.id != target_user.pk %}
          {% if is_follow %}
          <a href="{% url 'notes:unfollow' target_user.pk %}" class="btn relationBtn red">unfollow</a>
          {% else %}
          <a href="{% url 'notes:follow' target_user.pk %}" class="btn relationBtn blue">follow</a>
          {% endif %}
        {% endif %}
      {% endif %}
    </div>

    <div class="user-header__info__relation">
      <a class="relation-text" href="{% url 'notes:user_follow_list' target_user.pk %}"><b>{{ num_follow }}</b> Follow</a>
      <a class="relation-text" href="{% url 'notes:user_follower_list' target_user.pk %}"><b>{{ num_follower }}</b> Follower</a>
    </div>


  </div>
</div>
<hr>
{% endblock content_header %}


{% block content %}
<div>
  {% for note in target_user_notes_list %}
  <div class="note-content">
    <div class="note-content__icon">
      <a href="{% url 'notes:user_page' note.author.id %}">
        <img class="user-icon" src="{{ note.author.icon_small.url }}" alt="N">
      </a>
    </div>

    <div class="note-content__content">
      <p class="note-content__content-author"><a
              href="{% url 'notes:user_page' note.author.id %}">@{{ note.author }}</a> {{ note.get_format_created_at }}</p>
      <div class="note-content__content-area"
           onclick="location.href='{% url 'notes:note_detail' note.id %}'">
        {{ note.get_text_as_markdown }}
      </div>
    </div>
  </div>
  <hr>
  {% endfor %}
</div>
{% endblock content %}